// <auto-generated />
using System;
using Drippin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drippin.Migrations
{
    [DbContext(typeof(DrippinContext))]
    [Migration("20260423005036_DrippinTandas")]
    partial class DrippinTandas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drippin.Models.Acceso", b =>
                {
                    b.Property<int>("IdAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAcceso"));

                    b.Property<string>("DetalleFalla")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdAcceso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Acceso");
                });

            modelBuilder.Entity("Drippin.Models.CarritoItem", b =>
                {
                    b.Property<int>("ItemCarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCarritoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("proId")
                        .HasColumnType("int");

                    b.HasKey("ItemCarritoId");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("proId");

                    b.ToTable("ItemCarrito");
                });

            modelBuilder.Entity("Drippin.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("CatICO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Drippin.Models.Producto", b =>
                {
                    b.Property<int>("proId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<bool>("EsDestacado")
                        .HasColumnType("bit");

                    b.Property<string>("proDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proImagen2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proImagen3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proImagen4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proMedidas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("proPrecio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("proTandaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("prodCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("proId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("proTandaId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Drippin.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            NombreRol = "Cliente"
                        });
                });

            modelBuilder.Entity("Drippin.Models.Tanda", b =>
                {
                    b.Property<int>("TandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TandaId"));

                    b.Property<DateTime?>("TanFechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanFechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("TanNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TanVisible")
                        .HasColumnType("bit");

                    b.HasKey("TandaId");

                    b.ToTable("Tanda");
                });

            modelBuilder.Entity("Drippin.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime?>("FechaExpiracionToken")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsCorreo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Drippin.Models.Acceso", b =>
                {
                    b.HasOne("Drippin.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Drippin.Models.CarritoItem", b =>
                {
                    b.HasOne("Drippin.Models.Usuario", "Usuario")
                        .WithMany("CarritoItems")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drippin.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("proId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Drippin.Models.Producto", b =>
                {
                    b.HasOne("Drippin.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drippin.Models.Tanda", "Tanda")
                        .WithMany("Productos")
                        .HasForeignKey("proTandaId");

                    b.Navigation("Categoria");

                    b.Navigation("Tanda");
                });

            modelBuilder.Entity("Drippin.Models.Usuario", b =>
                {
                    b.HasOne("Drippin.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Drippin.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Drippin.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Drippin.Models.Tanda", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Drippin.Models.Usuario", b =>
                {
                    b.Navigation("CarritoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
